# Configuratio for Google-Chat FastAGI-Server

webhook: "<webhook url for the chatroom you want to send to>"
host: "127.0.0.1"  # IP the FastAGI-Server ist listening on, change it to 0.0.0.0 if you want network access
port: 4573  # Port the FastAGI-Server ist listening on - default is 4573 (Asterisk FastAGI Protocol)
timeout: 2  # Connection timeout for fastAGI requests in seconds
